version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["coolwsd"]

[main.add_domains.nextcloud_domain]
ask.fr = "Domaine nextcloud actuel"
ask.en = "Current nextcloud domain"
default = ""
type = "string"
bind = "__NEXTCLOUD_DOMAIN__:/etc/coolwsd/.env"

[main.add_domains]
name.en = "Extra domains"
name.fr = "Domaines supplémentaires"

[main.add_domains.extra_domain_1]
ask.fr = "Premier domaine supplémentaire"
ask.en = "First extra domain"
type = "string"
example = "nextcloud.example.com"
default = ""
bind = "__EXTRA_DOMAIN_1__:/etc/coolwsd/.env"

[main.add_domains.extra_domain_2]
ask.fr = "Deuxième domaine supplémentaire"
ask.en = "Second extra domain"
type = "string"
example = "nextcloud.example.com"
default = ""
bind = "__EXTRA_DOMAIN_2__:/etc/coolwsd/.env"

[main.add_domains.extra_domain_3]
ask.fr = "Troisième domaine supplémentaire"
ask.en = "Third extra domain"
type = "string"
example = "nextcloud.example.com"
default = ""
bind = "__EXTRA_DOMAIN_3__:/etc/coolwsd/.env"

[main.add_domains.extra_domain_4]
ask.fr = "Quatrième domaine supplémentaire"
ask.en = "Fourth extra domain"
type = "string"
example = "nextcloud.example.com"
default = ""
bind = "__EXTRA_DOMAIN_4__:/etc/coolwsd/.env"l"
